<?php
  // define('HTTP_SERVER', 'https://www.localpokies.co.nz');
  // define('HTTP_CATALOG_SERVER', 'https://www.localpokies.co.nz');
  // define('HTTPS_CATALOG_SERVER', 'https://www.localpokies.co.nz');
  define('HTTP_SERVER', 'http://localhost');
  define('HTTP_CATALOG_SERVER', 'http://localhost');
  define('HTTPS_CATALOG_SERVER', 'http://localhost');
  define('ENABLE_SSL_CATALOG', 'true');
  // define('DIR_FS_DOCUMENT_ROOT', '/home/customer/www/localpokies.co.nz/public_html/');
  define('DIR_FS_DOCUMENT_ROOT', 'C://Users/K/Documents/htdocs/');
  define('DIR_WS_ADMIN', '/admin/');
  // define('DIR_FS_ADMIN', '/home/customer/www/localpokies.co.nz/public_html/admin');
  define('DIR_FS_ADMIN', 'C://Users/K/Documents/htdocs/admin');
  define('DIR_WS_CATALOG', '/');
  // define('DIR_FS_CATALOG', '/home/customer/www/localpokies.co.nz/public_html/');
  define('DIR_FS_CATALOG', 'C://Users/K/Documents/htdocs/');
  define('DIR_WS_IMAGES', 'images/');
  define('DIR_WS_MANUALS', 'manuals/');
  define('DIR_WS_CATALOG_MANUALS', DIR_WS_CATALOG . 'manuals/');
  define('DIR_WS_ICONS', DIR_WS_IMAGES . 'icons/');
  define('DIR_WS_CATALOG_IMAGES', DIR_WS_CATALOG . 'images/');
  define('DIR_FS_CATALOG_MANUALS', DIR_FS_CATALOG . 'manuals/');
  define('DIR_WS_INCLUDES', 'includes/');
  define('DIR_WS_BOXES', DIR_WS_INCLUDES . 'boxes/');
  define('DIR_WS_FUNCTIONS', DIR_WS_INCLUDES . 'functions/');
  define('DIR_WS_CLASSES', DIR_WS_INCLUDES . 'classes/');
  define('DIR_WS_MODULES', DIR_WS_INCLUDES . 'modules/');
  define('DIR_WS_LANGUAGES', DIR_WS_INCLUDES . 'languages/');
  define('DIR_WS_CATALOG_LANGUAGES', DIR_WS_CATALOG . 'includes/languages/');
  define('DIR_FS_CATALOG_LANGUAGES', DIR_FS_CATALOG . 'includes/languages/');
  define('DIR_FS_CATALOG_IMAGES', DIR_FS_CATALOG . 'images/');
  define('DIR_FS_CATALOG_MODULES', DIR_FS_CATALOG . 'includes/modules/');
  define('DIR_FS_BACKUP', DIR_FS_ADMIN . 'backups/');

  define('DB_SERVER', '192.168.123.22');
  define('DB_SERVER_USERNAME', 'guest');
  define('DB_SERVER_PASSWORD', '');
  define('DB_DATABASE', 'dbaru7n9y5jped');
  define('USE_PCONNECT', 'false');
  define('STORE_SESSIONS', 'mysql');
?>
